In [1]:
import math

In [2]:
math.pi

3.141592653589793

In [3]:
math.e

2.718281828459045

In [4]:
math.inf

inf

In [5]:
math.ceil(7.8)

8

In [6]:
math.floor(2.5)

2

In [7]:
float_list = [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1]

In [8]:
sum(float_list)

0.9999999999999999

In [9]:
math.fsum(float_list)

1.0

In [10]:
math.gcd(30, 20)

10

In [11]:
math.gcd(3343, 223)

1

In [12]:
!pip install numpy

In [13]:
import numpy as np

In [15]:
some_list = [1,2,3,4,5,6,7]
type(some_list)

list

In [16]:
some_array = np.array(some_list)
type(some_array)

numpy.ndarray

In [17]:
some_array

array([1, 2, 3, 4, 5, 6, 7])

In [18]:
ones_array = np.ones(5)
ones_array

array([1., 1., 1., 1., 1.])

In [19]:
range_array = np.arange(8)
range_array

array([0, 1, 2, 3, 4, 5, 6, 7])

In [20]:
reshaped_array = range_array.reshape(2, 4)
reshaped_array

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [21]:
reshaped_array = range_array.reshape(4, 2)
reshaped_array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [23]:
random_array = np.random.random((4,5))
random_array

array([[0.05348653, 0.10263978, 0.28387483, 0.87024715, 0.90526615],
       [0.82477689, 0.12578914, 0.56409561, 0.44277286, 0.48412822],
       [0.45322644, 0.37540065, 0.97752546, 0.40898363, 0.4943376 ],
       [0.44114954, 0.73340689, 0.32786202, 0.60362338, 0.20442443]])

In [24]:
mean = np.mean(range_array)
mean

3.5

In [25]:
median = np.median(range_array)
median

3.5

In [26]:
var = np.var(range_array)
var

5.25

In [27]:
std = np.std(range_array)
std

2.29128784747792

In [28]:
!pip install pandas

In [31]:
import pandas as pd

In [32]:
df = pd.DataFrame({
        'name': ['John','Alice','Bob','Eileen','Rob'],
        'gender': ['Male','Female','Male','Female','Male'],
        'age': [45,20,30,14,67]
})

In [33]:
df

name  gender  age
0    John    Male   45
1   Alice  Female   20
2     Bob    Male   30
3  Eileen  Female   14
4     Rob    Male   67

In [34]:
df.describe()

age
count   5.000000
mean   35.200000
std    21.300235
min    14.000000
25%    20.000000
50%    30.000000
75%    45.000000
max    67.000000

In [35]:
subset_df = df[['name','age']]
subset_df

name  age
0    John   45
1   Alice   20
2     Bob   30
3  Eileen   14
4     Rob   67